# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shruti/Desktop/fire/fire-spread

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shruti/Desktop/fire/fire-spread

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shruti/Desktop/fire/fire-spread/CMakeFiles /home/shruti/Desktop/fire/fire-spread/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shruti/Desktop/fire/fire-spread/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named f

# Build rule for target.
f : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 f
.PHONY : f

# fast build rule for target.
f/fast:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/build
.PHONY : f/fast

simulation.o: simulation.c.o
.PHONY : simulation.o

# target to build an object file
simulation.c.o:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/simulation.c.o
.PHONY : simulation.c.o

simulation.i: simulation.c.i
.PHONY : simulation.i

# target to preprocess a source file
simulation.c.i:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/simulation.c.i
.PHONY : simulation.c.i

simulation.s: simulation.c.s
.PHONY : simulation.s

# target to generate assembly for a file
simulation.c.s:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/simulation.c.s
.PHONY : simulation.c.s

spreads.o: spreads.c.o
.PHONY : spreads.o

# target to build an object file
spreads.c.o:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/spreads.c.o
.PHONY : spreads.c.o

spreads.i: spreads.c.i
.PHONY : spreads.i

# target to preprocess a source file
spreads.c.i:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/spreads.c.i
.PHONY : spreads.c.i

spreads.s: spreads.c.s
.PHONY : spreads.s

# target to generate assembly for a file
spreads.c.s:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/spreads.c.s
.PHONY : spreads.c.s

utils.o: utils.c.o
.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i
.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s
.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... f"
	@echo "... rebuild_cache"
	@echo "... simulation.o"
	@echo "... simulation.i"
	@echo "... simulation.s"
	@echo "... spreads.o"
	@echo "... spreads.i"
	@echo "... spreads.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

